services:
  - type: web
    name: domino-score-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
